call galm/bin/get-another-label.bat --categories galm/settings/SIM_categories.txt --cost galm/settings/SIM_costs.txt --gold data/local/gal/SIM/lb005_000_gold.txt --input data/local/gal/SIM/lb005_000_label.txt --eval data/local/gal/SIM/lb005_000_eval.txt > data/local/gal/SIM/lb005_000_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/SIM_categories.txt --cost galm/settings/SIM_costs.txt --gold data/local/gal/SIM/lb005_001_gold.txt --input data/local/gal/SIM/lb005_001_label.txt --eval data/local/gal/SIM/lb005_001_eval.txt > data/local/gal/SIM/lb005_001_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/SIM_categories.txt --cost galm/settings/SIM_costs.txt --gold data/local/gal/SIM/lb005_002_gold.txt --input data/local/gal/SIM/lb005_002_label.txt --eval data/local/gal/SIM/lb005_002_eval.txt > data/local/gal/SIM/lb005_002_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/SIM_categories.txt --cost galm/settings/SIM_costs.txt --gold data/local/gal/SIM/lb005_003_gold.txt --input data/local/gal/SIM/lb005_003_label.txt --eval data/local/gal/SIM/lb005_003_eval.txt > data/local/gal/SIM/lb005_003_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/SIM_categories.txt --cost galm/settings/SIM_costs.txt --gold data/local/gal/SIM/lb005_004_gold.txt --input data/local/gal/SIM/lb005_004_label.txt --eval data/local/gal/SIM/lb005_004_eval.txt > data/local/gal/SIM/lb005_004_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/SIM_categories.txt --cost galm/settings/SIM_costs.txt --gold data/local/gal/SIM/lb005_005_gold.txt --input data/local/gal/SIM/lb005_005_label.txt --eval data/local/gal/SIM/lb005_005_eval.txt > data/local/gal/SIM/lb005_005_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/SIM_categories.txt --cost galm/settings/SIM_costs.txt --gold data/local/gal/SIM/lb005_006_gold.txt --input data/local/gal/SIM/lb005_006_label.txt --eval data/local/gal/SIM/lb005_006_eval.txt > data/local/gal/SIM/lb005_006_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/SIM_categories.txt --cost galm/settings/SIM_costs.txt --gold data/local/gal/SIM/lb005_007_gold.txt --input data/local/gal/SIM/lb005_007_label.txt --eval data/local/gal/SIM/lb005_007_eval.txt > data/local/gal/SIM/lb005_007_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/SIM_categories.txt --cost galm/settings/SIM_costs.txt --gold data/local/gal/SIM/lb005_008_gold.txt --input data/local/gal/SIM/lb005_008_label.txt --eval data/local/gal/SIM/lb005_008_eval.txt > data/local/gal/SIM/lb005_008_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/SIM_categories.txt --cost galm/settings/SIM_costs.txt --gold data/local/gal/SIM/lb005_009_gold.txt --input data/local/gal/SIM/lb005_009_label.txt --eval data/local/gal/SIM/lb005_009_eval.txt > data/local/gal/SIM/lb005_009_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/SIM_categories.txt --cost galm/settings/SIM_costs.txt --gold data/local/gal/SIM/lb005_010_gold.txt --input data/local/gal/SIM/lb005_010_label.txt --eval data/local/gal/SIM/lb005_010_eval.txt > data/local/gal/SIM/lb005_010_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/SIM_categories.txt --cost galm/settings/SIM_costs.txt --gold data/local/gal/SIM/lb005_011_gold.txt --input data/local/gal/SIM/lb005_011_label.txt --eval data/local/gal/SIM/lb005_011_eval.txt > data/local/gal/SIM/lb005_011_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/SIM_categories.txt --cost galm/settings/SIM_costs.txt --gold data/local/gal/SIM/lb005_012_gold.txt --input data/local/gal/SIM/lb005_012_label.txt --eval data/local/gal/SIM/lb005_012_eval.txt > data/local/gal/SIM/lb005_012_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/SIM_categories.txt --cost galm/settings/SIM_costs.txt --gold data/local/gal/SIM/lb005_013_gold.txt --input data/local/gal/SIM/lb005_013_label.txt --eval data/local/gal/SIM/lb005_013_eval.txt > data/local/gal/SIM/lb005_013_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/SIM_categories.txt --cost galm/settings/SIM_costs.txt --gold data/local/gal/SIM/lb005_014_gold.txt --input data/local/gal/SIM/lb005_014_label.txt --eval data/local/gal/SIM/lb005_014_eval.txt > data/local/gal/SIM/lb005_014_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/SIM_categories.txt --cost galm/settings/SIM_costs.txt --gold data/local/gal/SIM/lb005_015_gold.txt --input data/local/gal/SIM/lb005_015_label.txt --eval data/local/gal/SIM/lb005_015_eval.txt > data/local/gal/SIM/lb005_015_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/SIM_categories.txt --cost galm/settings/SIM_costs.txt --gold data/local/gal/SIM/lb005_016_gold.txt --input data/local/gal/SIM/lb005_016_label.txt --eval data/local/gal/SIM/lb005_016_eval.txt > data/local/gal/SIM/lb005_016_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/SIM_categories.txt --cost galm/settings/SIM_costs.txt --gold data/local/gal/SIM/lb005_017_gold.txt --input data/local/gal/SIM/lb005_017_label.txt --eval data/local/gal/SIM/lb005_017_eval.txt > data/local/gal/SIM/lb005_017_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/SIM_categories.txt --cost galm/settings/SIM_costs.txt --gold data/local/gal/SIM/lb005_018_gold.txt --input data/local/gal/SIM/lb005_018_label.txt --eval data/local/gal/SIM/lb005_018_eval.txt > data/local/gal/SIM/lb005_018_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/SIM_categories.txt --cost galm/settings/SIM_costs.txt --gold data/local/gal/SIM/lb005_019_gold.txt --input data/local/gal/SIM/lb005_019_label.txt --eval data/local/gal/SIM/lb005_019_eval.txt > data/local/gal/SIM/lb005_019_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/SIM_categories.txt --cost galm/settings/SIM_costs.txt --gold data/local/gal/SIM/lb005_020_gold.txt --input data/local/gal/SIM/lb005_020_label.txt --eval data/local/gal/SIM/lb005_020_eval.txt > data/local/gal/SIM/lb005_020_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/SIM_categories.txt --cost galm/settings/SIM_costs.txt --gold data/local/gal/SIM/lb005_021_gold.txt --input data/local/gal/SIM/lb005_021_label.txt --eval data/local/gal/SIM/lb005_021_eval.txt > data/local/gal/SIM/lb005_021_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/SIM_categories.txt --cost galm/settings/SIM_costs.txt --gold data/local/gal/SIM/lb005_022_gold.txt --input data/local/gal/SIM/lb005_022_label.txt --eval data/local/gal/SIM/lb005_022_eval.txt > data/local/gal/SIM/lb005_022_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/SIM_categories.txt --cost galm/settings/SIM_costs.txt --gold data/local/gal/SIM/lb005_023_gold.txt --input data/local/gal/SIM/lb005_023_label.txt --eval data/local/gal/SIM/lb005_023_eval.txt > data/local/gal/SIM/lb005_023_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/SIM_categories.txt --cost galm/settings/SIM_costs.txt --gold data/local/gal/SIM/lb005_024_gold.txt --input data/local/gal/SIM/lb005_024_label.txt --eval data/local/gal/SIM/lb005_024_eval.txt > data/local/gal/SIM/lb005_024_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/SIM_categories.txt --cost galm/settings/SIM_costs.txt --gold data/local/gal/SIM/lb005_025_gold.txt --input data/local/gal/SIM/lb005_025_label.txt --eval data/local/gal/SIM/lb005_025_eval.txt > data/local/gal/SIM/lb005_025_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/SIM_categories.txt --cost galm/settings/SIM_costs.txt --gold data/local/gal/SIM/lb005_026_gold.txt --input data/local/gal/SIM/lb005_026_label.txt --eval data/local/gal/SIM/lb005_026_eval.txt > data/local/gal/SIM/lb005_026_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/SIM_categories.txt --cost galm/settings/SIM_costs.txt --gold data/local/gal/SIM/lb005_027_gold.txt --input data/local/gal/SIM/lb005_027_label.txt --eval data/local/gal/SIM/lb005_027_eval.txt > data/local/gal/SIM/lb005_027_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/SIM_categories.txt --cost galm/settings/SIM_costs.txt --gold data/local/gal/SIM/lb005_028_gold.txt --input data/local/gal/SIM/lb005_028_label.txt --eval data/local/gal/SIM/lb005_028_eval.txt > data/local/gal/SIM/lb005_028_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/SIM_categories.txt --cost galm/settings/SIM_costs.txt --gold data/local/gal/SIM/lb005_029_gold.txt --input data/local/gal/SIM/lb005_029_label.txt --eval data/local/gal/SIM/lb005_029_eval.txt > data/local/gal/SIM/lb005_029_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/SIM_categories.txt --cost galm/settings/SIM_costs.txt --gold data/local/gal/SIM/lb005_030_gold.txt --input data/local/gal/SIM/lb005_030_label.txt --eval data/local/gal/SIM/lb005_030_eval.txt > data/local/gal/SIM/lb005_030_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/SIM_categories.txt --cost galm/settings/SIM_costs.txt --gold data/local/gal/SIM/lb005_031_gold.txt --input data/local/gal/SIM/lb005_031_label.txt --eval data/local/gal/SIM/lb005_031_eval.txt > data/local/gal/SIM/lb005_031_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/SIM_categories.txt --cost galm/settings/SIM_costs.txt --gold data/local/gal/SIM/lb005_032_gold.txt --input data/local/gal/SIM/lb005_032_label.txt --eval data/local/gal/SIM/lb005_032_eval.txt > data/local/gal/SIM/lb005_032_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/SIM_categories.txt --cost galm/settings/SIM_costs.txt --gold data/local/gal/SIM/lb005_033_gold.txt --input data/local/gal/SIM/lb005_033_label.txt --eval data/local/gal/SIM/lb005_033_eval.txt > data/local/gal/SIM/lb005_033_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/SIM_categories.txt --cost galm/settings/SIM_costs.txt --gold data/local/gal/SIM/lb005_034_gold.txt --input data/local/gal/SIM/lb005_034_label.txt --eval data/local/gal/SIM/lb005_034_eval.txt > data/local/gal/SIM/lb005_034_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/SIM_categories.txt --cost galm/settings/SIM_costs.txt --gold data/local/gal/SIM/lb005_035_gold.txt --input data/local/gal/SIM/lb005_035_label.txt --eval data/local/gal/SIM/lb005_035_eval.txt > data/local/gal/SIM/lb005_035_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/SIM_categories.txt --cost galm/settings/SIM_costs.txt --gold data/local/gal/SIM/lb005_036_gold.txt --input data/local/gal/SIM/lb005_036_label.txt --eval data/local/gal/SIM/lb005_036_eval.txt > data/local/gal/SIM/lb005_036_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/SIM_categories.txt --cost galm/settings/SIM_costs.txt --gold data/local/gal/SIM/lb005_037_gold.txt --input data/local/gal/SIM/lb005_037_label.txt --eval data/local/gal/SIM/lb005_037_eval.txt > data/local/gal/SIM/lb005_037_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/SIM_categories.txt --cost galm/settings/SIM_costs.txt --gold data/local/gal/SIM/lb005_038_gold.txt --input data/local/gal/SIM/lb005_038_label.txt --eval data/local/gal/SIM/lb005_038_eval.txt > data/local/gal/SIM/lb005_038_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/SIM_categories.txt --cost galm/settings/SIM_costs.txt --gold data/local/gal/SIM/lb005_039_gold.txt --input data/local/gal/SIM/lb005_039_label.txt --eval data/local/gal/SIM/lb005_039_eval.txt > data/local/gal/SIM/lb005_039_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/SIM_categories.txt --cost galm/settings/SIM_costs.txt --gold data/local/gal/SIM/lb005_040_gold.txt --input data/local/gal/SIM/lb005_040_label.txt --eval data/local/gal/SIM/lb005_040_eval.txt > data/local/gal/SIM/lb005_040_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/SIM_categories.txt --cost galm/settings/SIM_costs.txt --gold data/local/gal/SIM/lb005_041_gold.txt --input data/local/gal/SIM/lb005_041_label.txt --eval data/local/gal/SIM/lb005_041_eval.txt > data/local/gal/SIM/lb005_041_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/SIM_categories.txt --cost galm/settings/SIM_costs.txt --gold data/local/gal/SIM/lb005_042_gold.txt --input data/local/gal/SIM/lb005_042_label.txt --eval data/local/gal/SIM/lb005_042_eval.txt > data/local/gal/SIM/lb005_042_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/SIM_categories.txt --cost galm/settings/SIM_costs.txt --gold data/local/gal/SIM/lb005_043_gold.txt --input data/local/gal/SIM/lb005_043_label.txt --eval data/local/gal/SIM/lb005_043_eval.txt > data/local/gal/SIM/lb005_043_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/SIM_categories.txt --cost galm/settings/SIM_costs.txt --gold data/local/gal/SIM/lb005_044_gold.txt --input data/local/gal/SIM/lb005_044_label.txt --eval data/local/gal/SIM/lb005_044_eval.txt > data/local/gal/SIM/lb005_044_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/SIM_categories.txt --cost galm/settings/SIM_costs.txt --gold data/local/gal/SIM/lb005_045_gold.txt --input data/local/gal/SIM/lb005_045_label.txt --eval data/local/gal/SIM/lb005_045_eval.txt > data/local/gal/SIM/lb005_045_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/SIM_categories.txt --cost galm/settings/SIM_costs.txt --gold data/local/gal/SIM/lb005_046_gold.txt --input data/local/gal/SIM/lb005_046_label.txt --eval data/local/gal/SIM/lb005_046_eval.txt > data/local/gal/SIM/lb005_046_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/SIM_categories.txt --cost galm/settings/SIM_costs.txt --gold data/local/gal/SIM/lb005_047_gold.txt --input data/local/gal/SIM/lb005_047_label.txt --eval data/local/gal/SIM/lb005_047_eval.txt > data/local/gal/SIM/lb005_047_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/SIM_categories.txt --cost galm/settings/SIM_costs.txt --gold data/local/gal/SIM/lb005_048_gold.txt --input data/local/gal/SIM/lb005_048_label.txt --eval data/local/gal/SIM/lb005_048_eval.txt > data/local/gal/SIM/lb005_048_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/SIM_categories.txt --cost galm/settings/SIM_costs.txt --gold data/local/gal/SIM/lb005_049_gold.txt --input data/local/gal/SIM/lb005_049_label.txt --eval data/local/gal/SIM/lb005_049_eval.txt > data/local/gal/SIM/lb005_049_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/DIFF_categories.txt --cost galm/settings/DIFF_costs.txt --gold data/local/gal/DIFF/lb005_000_gold.txt --input data/local/gal/DIFF/lb005_000_label.txt --eval data/local/gal/DIFF/lb005_000_eval.txt > data/local/gal/DIFF/lb005_000_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/DIFF_categories.txt --cost galm/settings/DIFF_costs.txt --gold data/local/gal/DIFF/lb005_001_gold.txt --input data/local/gal/DIFF/lb005_001_label.txt --eval data/local/gal/DIFF/lb005_001_eval.txt > data/local/gal/DIFF/lb005_001_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/DIFF_categories.txt --cost galm/settings/DIFF_costs.txt --gold data/local/gal/DIFF/lb005_002_gold.txt --input data/local/gal/DIFF/lb005_002_label.txt --eval data/local/gal/DIFF/lb005_002_eval.txt > data/local/gal/DIFF/lb005_002_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/DIFF_categories.txt --cost galm/settings/DIFF_costs.txt --gold data/local/gal/DIFF/lb005_003_gold.txt --input data/local/gal/DIFF/lb005_003_label.txt --eval data/local/gal/DIFF/lb005_003_eval.txt > data/local/gal/DIFF/lb005_003_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/DIFF_categories.txt --cost galm/settings/DIFF_costs.txt --gold data/local/gal/DIFF/lb005_004_gold.txt --input data/local/gal/DIFF/lb005_004_label.txt --eval data/local/gal/DIFF/lb005_004_eval.txt > data/local/gal/DIFF/lb005_004_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/DIFF_categories.txt --cost galm/settings/DIFF_costs.txt --gold data/local/gal/DIFF/lb005_005_gold.txt --input data/local/gal/DIFF/lb005_005_label.txt --eval data/local/gal/DIFF/lb005_005_eval.txt > data/local/gal/DIFF/lb005_005_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/DIFF_categories.txt --cost galm/settings/DIFF_costs.txt --gold data/local/gal/DIFF/lb005_006_gold.txt --input data/local/gal/DIFF/lb005_006_label.txt --eval data/local/gal/DIFF/lb005_006_eval.txt > data/local/gal/DIFF/lb005_006_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/DIFF_categories.txt --cost galm/settings/DIFF_costs.txt --gold data/local/gal/DIFF/lb005_007_gold.txt --input data/local/gal/DIFF/lb005_007_label.txt --eval data/local/gal/DIFF/lb005_007_eval.txt > data/local/gal/DIFF/lb005_007_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/DIFF_categories.txt --cost galm/settings/DIFF_costs.txt --gold data/local/gal/DIFF/lb005_008_gold.txt --input data/local/gal/DIFF/lb005_008_label.txt --eval data/local/gal/DIFF/lb005_008_eval.txt > data/local/gal/DIFF/lb005_008_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/DIFF_categories.txt --cost galm/settings/DIFF_costs.txt --gold data/local/gal/DIFF/lb005_009_gold.txt --input data/local/gal/DIFF/lb005_009_label.txt --eval data/local/gal/DIFF/lb005_009_eval.txt > data/local/gal/DIFF/lb005_009_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/DIFF_categories.txt --cost galm/settings/DIFF_costs.txt --gold data/local/gal/DIFF/lb005_010_gold.txt --input data/local/gal/DIFF/lb005_010_label.txt --eval data/local/gal/DIFF/lb005_010_eval.txt > data/local/gal/DIFF/lb005_010_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/DIFF_categories.txt --cost galm/settings/DIFF_costs.txt --gold data/local/gal/DIFF/lb005_011_gold.txt --input data/local/gal/DIFF/lb005_011_label.txt --eval data/local/gal/DIFF/lb005_011_eval.txt > data/local/gal/DIFF/lb005_011_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/DIFF_categories.txt --cost galm/settings/DIFF_costs.txt --gold data/local/gal/DIFF/lb005_012_gold.txt --input data/local/gal/DIFF/lb005_012_label.txt --eval data/local/gal/DIFF/lb005_012_eval.txt > data/local/gal/DIFF/lb005_012_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/DIFF_categories.txt --cost galm/settings/DIFF_costs.txt --gold data/local/gal/DIFF/lb005_013_gold.txt --input data/local/gal/DIFF/lb005_013_label.txt --eval data/local/gal/DIFF/lb005_013_eval.txt > data/local/gal/DIFF/lb005_013_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/DIFF_categories.txt --cost galm/settings/DIFF_costs.txt --gold data/local/gal/DIFF/lb005_014_gold.txt --input data/local/gal/DIFF/lb005_014_label.txt --eval data/local/gal/DIFF/lb005_014_eval.txt > data/local/gal/DIFF/lb005_014_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/DIFF_categories.txt --cost galm/settings/DIFF_costs.txt --gold data/local/gal/DIFF/lb005_015_gold.txt --input data/local/gal/DIFF/lb005_015_label.txt --eval data/local/gal/DIFF/lb005_015_eval.txt > data/local/gal/DIFF/lb005_015_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/DIFF_categories.txt --cost galm/settings/DIFF_costs.txt --gold data/local/gal/DIFF/lb005_016_gold.txt --input data/local/gal/DIFF/lb005_016_label.txt --eval data/local/gal/DIFF/lb005_016_eval.txt > data/local/gal/DIFF/lb005_016_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/DIFF_categories.txt --cost galm/settings/DIFF_costs.txt --gold data/local/gal/DIFF/lb005_017_gold.txt --input data/local/gal/DIFF/lb005_017_label.txt --eval data/local/gal/DIFF/lb005_017_eval.txt > data/local/gal/DIFF/lb005_017_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/DIFF_categories.txt --cost galm/settings/DIFF_costs.txt --gold data/local/gal/DIFF/lb005_018_gold.txt --input data/local/gal/DIFF/lb005_018_label.txt --eval data/local/gal/DIFF/lb005_018_eval.txt > data/local/gal/DIFF/lb005_018_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/DIFF_categories.txt --cost galm/settings/DIFF_costs.txt --gold data/local/gal/DIFF/lb005_019_gold.txt --input data/local/gal/DIFF/lb005_019_label.txt --eval data/local/gal/DIFF/lb005_019_eval.txt > data/local/gal/DIFF/lb005_019_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/DIFF_categories.txt --cost galm/settings/DIFF_costs.txt --gold data/local/gal/DIFF/lb005_020_gold.txt --input data/local/gal/DIFF/lb005_020_label.txt --eval data/local/gal/DIFF/lb005_020_eval.txt > data/local/gal/DIFF/lb005_020_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/DIFF_categories.txt --cost galm/settings/DIFF_costs.txt --gold data/local/gal/DIFF/lb005_021_gold.txt --input data/local/gal/DIFF/lb005_021_label.txt --eval data/local/gal/DIFF/lb005_021_eval.txt > data/local/gal/DIFF/lb005_021_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/DIFF_categories.txt --cost galm/settings/DIFF_costs.txt --gold data/local/gal/DIFF/lb005_022_gold.txt --input data/local/gal/DIFF/lb005_022_label.txt --eval data/local/gal/DIFF/lb005_022_eval.txt > data/local/gal/DIFF/lb005_022_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/DIFF_categories.txt --cost galm/settings/DIFF_costs.txt --gold data/local/gal/DIFF/lb005_023_gold.txt --input data/local/gal/DIFF/lb005_023_label.txt --eval data/local/gal/DIFF/lb005_023_eval.txt > data/local/gal/DIFF/lb005_023_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/DIFF_categories.txt --cost galm/settings/DIFF_costs.txt --gold data/local/gal/DIFF/lb005_024_gold.txt --input data/local/gal/DIFF/lb005_024_label.txt --eval data/local/gal/DIFF/lb005_024_eval.txt > data/local/gal/DIFF/lb005_024_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/DIFF_categories.txt --cost galm/settings/DIFF_costs.txt --gold data/local/gal/DIFF/lb005_025_gold.txt --input data/local/gal/DIFF/lb005_025_label.txt --eval data/local/gal/DIFF/lb005_025_eval.txt > data/local/gal/DIFF/lb005_025_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/DIFF_categories.txt --cost galm/settings/DIFF_costs.txt --gold data/local/gal/DIFF/lb005_026_gold.txt --input data/local/gal/DIFF/lb005_026_label.txt --eval data/local/gal/DIFF/lb005_026_eval.txt > data/local/gal/DIFF/lb005_026_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/DIFF_categories.txt --cost galm/settings/DIFF_costs.txt --gold data/local/gal/DIFF/lb005_027_gold.txt --input data/local/gal/DIFF/lb005_027_label.txt --eval data/local/gal/DIFF/lb005_027_eval.txt > data/local/gal/DIFF/lb005_027_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/DIFF_categories.txt --cost galm/settings/DIFF_costs.txt --gold data/local/gal/DIFF/lb005_028_gold.txt --input data/local/gal/DIFF/lb005_028_label.txt --eval data/local/gal/DIFF/lb005_028_eval.txt > data/local/gal/DIFF/lb005_028_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/DIFF_categories.txt --cost galm/settings/DIFF_costs.txt --gold data/local/gal/DIFF/lb005_029_gold.txt --input data/local/gal/DIFF/lb005_029_label.txt --eval data/local/gal/DIFF/lb005_029_eval.txt > data/local/gal/DIFF/lb005_029_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/DIFF_categories.txt --cost galm/settings/DIFF_costs.txt --gold data/local/gal/DIFF/lb005_030_gold.txt --input data/local/gal/DIFF/lb005_030_label.txt --eval data/local/gal/DIFF/lb005_030_eval.txt > data/local/gal/DIFF/lb005_030_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/DIFF_categories.txt --cost galm/settings/DIFF_costs.txt --gold data/local/gal/DIFF/lb005_031_gold.txt --input data/local/gal/DIFF/lb005_031_label.txt --eval data/local/gal/DIFF/lb005_031_eval.txt > data/local/gal/DIFF/lb005_031_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/DIFF_categories.txt --cost galm/settings/DIFF_costs.txt --gold data/local/gal/DIFF/lb005_032_gold.txt --input data/local/gal/DIFF/lb005_032_label.txt --eval data/local/gal/DIFF/lb005_032_eval.txt > data/local/gal/DIFF/lb005_032_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/DIFF_categories.txt --cost galm/settings/DIFF_costs.txt --gold data/local/gal/DIFF/lb005_033_gold.txt --input data/local/gal/DIFF/lb005_033_label.txt --eval data/local/gal/DIFF/lb005_033_eval.txt > data/local/gal/DIFF/lb005_033_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/DIFF_categories.txt --cost galm/settings/DIFF_costs.txt --gold data/local/gal/DIFF/lb005_034_gold.txt --input data/local/gal/DIFF/lb005_034_label.txt --eval data/local/gal/DIFF/lb005_034_eval.txt > data/local/gal/DIFF/lb005_034_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/DIFF_categories.txt --cost galm/settings/DIFF_costs.txt --gold data/local/gal/DIFF/lb005_035_gold.txt --input data/local/gal/DIFF/lb005_035_label.txt --eval data/local/gal/DIFF/lb005_035_eval.txt > data/local/gal/DIFF/lb005_035_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/DIFF_categories.txt --cost galm/settings/DIFF_costs.txt --gold data/local/gal/DIFF/lb005_036_gold.txt --input data/local/gal/DIFF/lb005_036_label.txt --eval data/local/gal/DIFF/lb005_036_eval.txt > data/local/gal/DIFF/lb005_036_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/DIFF_categories.txt --cost galm/settings/DIFF_costs.txt --gold data/local/gal/DIFF/lb005_037_gold.txt --input data/local/gal/DIFF/lb005_037_label.txt --eval data/local/gal/DIFF/lb005_037_eval.txt > data/local/gal/DIFF/lb005_037_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/DIFF_categories.txt --cost galm/settings/DIFF_costs.txt --gold data/local/gal/DIFF/lb005_038_gold.txt --input data/local/gal/DIFF/lb005_038_label.txt --eval data/local/gal/DIFF/lb005_038_eval.txt > data/local/gal/DIFF/lb005_038_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/DIFF_categories.txt --cost galm/settings/DIFF_costs.txt --gold data/local/gal/DIFF/lb005_039_gold.txt --input data/local/gal/DIFF/lb005_039_label.txt --eval data/local/gal/DIFF/lb005_039_eval.txt > data/local/gal/DIFF/lb005_039_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/DIFF_categories.txt --cost galm/settings/DIFF_costs.txt --gold data/local/gal/DIFF/lb005_040_gold.txt --input data/local/gal/DIFF/lb005_040_label.txt --eval data/local/gal/DIFF/lb005_040_eval.txt > data/local/gal/DIFF/lb005_040_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/DIFF_categories.txt --cost galm/settings/DIFF_costs.txt --gold data/local/gal/DIFF/lb005_041_gold.txt --input data/local/gal/DIFF/lb005_041_label.txt --eval data/local/gal/DIFF/lb005_041_eval.txt > data/local/gal/DIFF/lb005_041_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/DIFF_categories.txt --cost galm/settings/DIFF_costs.txt --gold data/local/gal/DIFF/lb005_042_gold.txt --input data/local/gal/DIFF/lb005_042_label.txt --eval data/local/gal/DIFF/lb005_042_eval.txt > data/local/gal/DIFF/lb005_042_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/DIFF_categories.txt --cost galm/settings/DIFF_costs.txt --gold data/local/gal/DIFF/lb005_043_gold.txt --input data/local/gal/DIFF/lb005_043_label.txt --eval data/local/gal/DIFF/lb005_043_eval.txt > data/local/gal/DIFF/lb005_043_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/DIFF_categories.txt --cost galm/settings/DIFF_costs.txt --gold data/local/gal/DIFF/lb005_044_gold.txt --input data/local/gal/DIFF/lb005_044_label.txt --eval data/local/gal/DIFF/lb005_044_eval.txt > data/local/gal/DIFF/lb005_044_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/DIFF_categories.txt --cost galm/settings/DIFF_costs.txt --gold data/local/gal/DIFF/lb005_045_gold.txt --input data/local/gal/DIFF/lb005_045_label.txt --eval data/local/gal/DIFF/lb005_045_eval.txt > data/local/gal/DIFF/lb005_045_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/DIFF_categories.txt --cost galm/settings/DIFF_costs.txt --gold data/local/gal/DIFF/lb005_046_gold.txt --input data/local/gal/DIFF/lb005_046_label.txt --eval data/local/gal/DIFF/lb005_046_eval.txt > data/local/gal/DIFF/lb005_046_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/DIFF_categories.txt --cost galm/settings/DIFF_costs.txt --gold data/local/gal/DIFF/lb005_047_gold.txt --input data/local/gal/DIFF/lb005_047_label.txt --eval data/local/gal/DIFF/lb005_047_eval.txt > data/local/gal/DIFF/lb005_047_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/DIFF_categories.txt --cost galm/settings/DIFF_costs.txt --gold data/local/gal/DIFF/lb005_048_gold.txt --input data/local/gal/DIFF/lb005_048_label.txt --eval data/local/gal/DIFF/lb005_048_eval.txt > data/local/gal/DIFF/lb005_048_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/DIFF_categories.txt --cost galm/settings/DIFF_costs.txt --gold data/local/gal/DIFF/lb005_049_gold.txt --input data/local/gal/DIFF/lb005_049_label.txt --eval data/local/gal/DIFF/lb005_049_eval.txt > data/local/gal/DIFF/lb005_049_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/GSIM_categories.txt --cost galm/settings/GSIM_costs.txt --gold data/local/gal/GSIM/lb005_000_gold.txt --input data/local/gal/GSIM/lb005_000_label.txt --eval data/local/gal/GSIM/lb005_000_eval.txt > data/local/gal/GSIM/lb005_000_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/GSIM_categories.txt --cost galm/settings/GSIM_costs.txt --gold data/local/gal/GSIM/lb005_001_gold.txt --input data/local/gal/GSIM/lb005_001_label.txt --eval data/local/gal/GSIM/lb005_001_eval.txt > data/local/gal/GSIM/lb005_001_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/GSIM_categories.txt --cost galm/settings/GSIM_costs.txt --gold data/local/gal/GSIM/lb005_002_gold.txt --input data/local/gal/GSIM/lb005_002_label.txt --eval data/local/gal/GSIM/lb005_002_eval.txt > data/local/gal/GSIM/lb005_002_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/GSIM_categories.txt --cost galm/settings/GSIM_costs.txt --gold data/local/gal/GSIM/lb005_003_gold.txt --input data/local/gal/GSIM/lb005_003_label.txt --eval data/local/gal/GSIM/lb005_003_eval.txt > data/local/gal/GSIM/lb005_003_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/GSIM_categories.txt --cost galm/settings/GSIM_costs.txt --gold data/local/gal/GSIM/lb005_004_gold.txt --input data/local/gal/GSIM/lb005_004_label.txt --eval data/local/gal/GSIM/lb005_004_eval.txt > data/local/gal/GSIM/lb005_004_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/GSIM_categories.txt --cost galm/settings/GSIM_costs.txt --gold data/local/gal/GSIM/lb005_005_gold.txt --input data/local/gal/GSIM/lb005_005_label.txt --eval data/local/gal/GSIM/lb005_005_eval.txt > data/local/gal/GSIM/lb005_005_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/GSIM_categories.txt --cost galm/settings/GSIM_costs.txt --gold data/local/gal/GSIM/lb005_006_gold.txt --input data/local/gal/GSIM/lb005_006_label.txt --eval data/local/gal/GSIM/lb005_006_eval.txt > data/local/gal/GSIM/lb005_006_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/GSIM_categories.txt --cost galm/settings/GSIM_costs.txt --gold data/local/gal/GSIM/lb005_007_gold.txt --input data/local/gal/GSIM/lb005_007_label.txt --eval data/local/gal/GSIM/lb005_007_eval.txt > data/local/gal/GSIM/lb005_007_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/GSIM_categories.txt --cost galm/settings/GSIM_costs.txt --gold data/local/gal/GSIM/lb005_008_gold.txt --input data/local/gal/GSIM/lb005_008_label.txt --eval data/local/gal/GSIM/lb005_008_eval.txt > data/local/gal/GSIM/lb005_008_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/GSIM_categories.txt --cost galm/settings/GSIM_costs.txt --gold data/local/gal/GSIM/lb005_009_gold.txt --input data/local/gal/GSIM/lb005_009_label.txt --eval data/local/gal/GSIM/lb005_009_eval.txt > data/local/gal/GSIM/lb005_009_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/GSIM_categories.txt --cost galm/settings/GSIM_costs.txt --gold data/local/gal/GSIM/lb005_010_gold.txt --input data/local/gal/GSIM/lb005_010_label.txt --eval data/local/gal/GSIM/lb005_010_eval.txt > data/local/gal/GSIM/lb005_010_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/GSIM_categories.txt --cost galm/settings/GSIM_costs.txt --gold data/local/gal/GSIM/lb005_011_gold.txt --input data/local/gal/GSIM/lb005_011_label.txt --eval data/local/gal/GSIM/lb005_011_eval.txt > data/local/gal/GSIM/lb005_011_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/GSIM_categories.txt --cost galm/settings/GSIM_costs.txt --gold data/local/gal/GSIM/lb005_012_gold.txt --input data/local/gal/GSIM/lb005_012_label.txt --eval data/local/gal/GSIM/lb005_012_eval.txt > data/local/gal/GSIM/lb005_012_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/GSIM_categories.txt --cost galm/settings/GSIM_costs.txt --gold data/local/gal/GSIM/lb005_013_gold.txt --input data/local/gal/GSIM/lb005_013_label.txt --eval data/local/gal/GSIM/lb005_013_eval.txt > data/local/gal/GSIM/lb005_013_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/GSIM_categories.txt --cost galm/settings/GSIM_costs.txt --gold data/local/gal/GSIM/lb005_014_gold.txt --input data/local/gal/GSIM/lb005_014_label.txt --eval data/local/gal/GSIM/lb005_014_eval.txt > data/local/gal/GSIM/lb005_014_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/GSIM_categories.txt --cost galm/settings/GSIM_costs.txt --gold data/local/gal/GSIM/lb005_015_gold.txt --input data/local/gal/GSIM/lb005_015_label.txt --eval data/local/gal/GSIM/lb005_015_eval.txt > data/local/gal/GSIM/lb005_015_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/GSIM_categories.txt --cost galm/settings/GSIM_costs.txt --gold data/local/gal/GSIM/lb005_016_gold.txt --input data/local/gal/GSIM/lb005_016_label.txt --eval data/local/gal/GSIM/lb005_016_eval.txt > data/local/gal/GSIM/lb005_016_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/GSIM_categories.txt --cost galm/settings/GSIM_costs.txt --gold data/local/gal/GSIM/lb005_017_gold.txt --input data/local/gal/GSIM/lb005_017_label.txt --eval data/local/gal/GSIM/lb005_017_eval.txt > data/local/gal/GSIM/lb005_017_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/GSIM_categories.txt --cost galm/settings/GSIM_costs.txt --gold data/local/gal/GSIM/lb005_018_gold.txt --input data/local/gal/GSIM/lb005_018_label.txt --eval data/local/gal/GSIM/lb005_018_eval.txt > data/local/gal/GSIM/lb005_018_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/GSIM_categories.txt --cost galm/settings/GSIM_costs.txt --gold data/local/gal/GSIM/lb005_019_gold.txt --input data/local/gal/GSIM/lb005_019_label.txt --eval data/local/gal/GSIM/lb005_019_eval.txt > data/local/gal/GSIM/lb005_019_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/GSIM_categories.txt --cost galm/settings/GSIM_costs.txt --gold data/local/gal/GSIM/lb005_020_gold.txt --input data/local/gal/GSIM/lb005_020_label.txt --eval data/local/gal/GSIM/lb005_020_eval.txt > data/local/gal/GSIM/lb005_020_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/GSIM_categories.txt --cost galm/settings/GSIM_costs.txt --gold data/local/gal/GSIM/lb005_021_gold.txt --input data/local/gal/GSIM/lb005_021_label.txt --eval data/local/gal/GSIM/lb005_021_eval.txt > data/local/gal/GSIM/lb005_021_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/GSIM_categories.txt --cost galm/settings/GSIM_costs.txt --gold data/local/gal/GSIM/lb005_022_gold.txt --input data/local/gal/GSIM/lb005_022_label.txt --eval data/local/gal/GSIM/lb005_022_eval.txt > data/local/gal/GSIM/lb005_022_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/GSIM_categories.txt --cost galm/settings/GSIM_costs.txt --gold data/local/gal/GSIM/lb005_023_gold.txt --input data/local/gal/GSIM/lb005_023_label.txt --eval data/local/gal/GSIM/lb005_023_eval.txt > data/local/gal/GSIM/lb005_023_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/GSIM_categories.txt --cost galm/settings/GSIM_costs.txt --gold data/local/gal/GSIM/lb005_024_gold.txt --input data/local/gal/GSIM/lb005_024_label.txt --eval data/local/gal/GSIM/lb005_024_eval.txt > data/local/gal/GSIM/lb005_024_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/GSIM_categories.txt --cost galm/settings/GSIM_costs.txt --gold data/local/gal/GSIM/lb005_025_gold.txt --input data/local/gal/GSIM/lb005_025_label.txt --eval data/local/gal/GSIM/lb005_025_eval.txt > data/local/gal/GSIM/lb005_025_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/GSIM_categories.txt --cost galm/settings/GSIM_costs.txt --gold data/local/gal/GSIM/lb005_026_gold.txt --input data/local/gal/GSIM/lb005_026_label.txt --eval data/local/gal/GSIM/lb005_026_eval.txt > data/local/gal/GSIM/lb005_026_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/GSIM_categories.txt --cost galm/settings/GSIM_costs.txt --gold data/local/gal/GSIM/lb005_027_gold.txt --input data/local/gal/GSIM/lb005_027_label.txt --eval data/local/gal/GSIM/lb005_027_eval.txt > data/local/gal/GSIM/lb005_027_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/GSIM_categories.txt --cost galm/settings/GSIM_costs.txt --gold data/local/gal/GSIM/lb005_028_gold.txt --input data/local/gal/GSIM/lb005_028_label.txt --eval data/local/gal/GSIM/lb005_028_eval.txt > data/local/gal/GSIM/lb005_028_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/GSIM_categories.txt --cost galm/settings/GSIM_costs.txt --gold data/local/gal/GSIM/lb005_029_gold.txt --input data/local/gal/GSIM/lb005_029_label.txt --eval data/local/gal/GSIM/lb005_029_eval.txt > data/local/gal/GSIM/lb005_029_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/GSIM_categories.txt --cost galm/settings/GSIM_costs.txt --gold data/local/gal/GSIM/lb005_030_gold.txt --input data/local/gal/GSIM/lb005_030_label.txt --eval data/local/gal/GSIM/lb005_030_eval.txt > data/local/gal/GSIM/lb005_030_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/GSIM_categories.txt --cost galm/settings/GSIM_costs.txt --gold data/local/gal/GSIM/lb005_031_gold.txt --input data/local/gal/GSIM/lb005_031_label.txt --eval data/local/gal/GSIM/lb005_031_eval.txt > data/local/gal/GSIM/lb005_031_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/GSIM_categories.txt --cost galm/settings/GSIM_costs.txt --gold data/local/gal/GSIM/lb005_032_gold.txt --input data/local/gal/GSIM/lb005_032_label.txt --eval data/local/gal/GSIM/lb005_032_eval.txt > data/local/gal/GSIM/lb005_032_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/GSIM_categories.txt --cost galm/settings/GSIM_costs.txt --gold data/local/gal/GSIM/lb005_033_gold.txt --input data/local/gal/GSIM/lb005_033_label.txt --eval data/local/gal/GSIM/lb005_033_eval.txt > data/local/gal/GSIM/lb005_033_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/GSIM_categories.txt --cost galm/settings/GSIM_costs.txt --gold data/local/gal/GSIM/lb005_034_gold.txt --input data/local/gal/GSIM/lb005_034_label.txt --eval data/local/gal/GSIM/lb005_034_eval.txt > data/local/gal/GSIM/lb005_034_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/GSIM_categories.txt --cost galm/settings/GSIM_costs.txt --gold data/local/gal/GSIM/lb005_035_gold.txt --input data/local/gal/GSIM/lb005_035_label.txt --eval data/local/gal/GSIM/lb005_035_eval.txt > data/local/gal/GSIM/lb005_035_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/GSIM_categories.txt --cost galm/settings/GSIM_costs.txt --gold data/local/gal/GSIM/lb005_036_gold.txt --input data/local/gal/GSIM/lb005_036_label.txt --eval data/local/gal/GSIM/lb005_036_eval.txt > data/local/gal/GSIM/lb005_036_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/GSIM_categories.txt --cost galm/settings/GSIM_costs.txt --gold data/local/gal/GSIM/lb005_037_gold.txt --input data/local/gal/GSIM/lb005_037_label.txt --eval data/local/gal/GSIM/lb005_037_eval.txt > data/local/gal/GSIM/lb005_037_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/GSIM_categories.txt --cost galm/settings/GSIM_costs.txt --gold data/local/gal/GSIM/lb005_038_gold.txt --input data/local/gal/GSIM/lb005_038_label.txt --eval data/local/gal/GSIM/lb005_038_eval.txt > data/local/gal/GSIM/lb005_038_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/GSIM_categories.txt --cost galm/settings/GSIM_costs.txt --gold data/local/gal/GSIM/lb005_039_gold.txt --input data/local/gal/GSIM/lb005_039_label.txt --eval data/local/gal/GSIM/lb005_039_eval.txt > data/local/gal/GSIM/lb005_039_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/GSIM_categories.txt --cost galm/settings/GSIM_costs.txt --gold data/local/gal/GSIM/lb005_040_gold.txt --input data/local/gal/GSIM/lb005_040_label.txt --eval data/local/gal/GSIM/lb005_040_eval.txt > data/local/gal/GSIM/lb005_040_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/GSIM_categories.txt --cost galm/settings/GSIM_costs.txt --gold data/local/gal/GSIM/lb005_041_gold.txt --input data/local/gal/GSIM/lb005_041_label.txt --eval data/local/gal/GSIM/lb005_041_eval.txt > data/local/gal/GSIM/lb005_041_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/GSIM_categories.txt --cost galm/settings/GSIM_costs.txt --gold data/local/gal/GSIM/lb005_042_gold.txt --input data/local/gal/GSIM/lb005_042_label.txt --eval data/local/gal/GSIM/lb005_042_eval.txt > data/local/gal/GSIM/lb005_042_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/GSIM_categories.txt --cost galm/settings/GSIM_costs.txt --gold data/local/gal/GSIM/lb005_043_gold.txt --input data/local/gal/GSIM/lb005_043_label.txt --eval data/local/gal/GSIM/lb005_043_eval.txt > data/local/gal/GSIM/lb005_043_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/GSIM_categories.txt --cost galm/settings/GSIM_costs.txt --gold data/local/gal/GSIM/lb005_044_gold.txt --input data/local/gal/GSIM/lb005_044_label.txt --eval data/local/gal/GSIM/lb005_044_eval.txt > data/local/gal/GSIM/lb005_044_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/GSIM_categories.txt --cost galm/settings/GSIM_costs.txt --gold data/local/gal/GSIM/lb005_045_gold.txt --input data/local/gal/GSIM/lb005_045_label.txt --eval data/local/gal/GSIM/lb005_045_eval.txt > data/local/gal/GSIM/lb005_045_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/GSIM_categories.txt --cost galm/settings/GSIM_costs.txt --gold data/local/gal/GSIM/lb005_046_gold.txt --input data/local/gal/GSIM/lb005_046_label.txt --eval data/local/gal/GSIM/lb005_046_eval.txt > data/local/gal/GSIM/lb005_046_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/GSIM_categories.txt --cost galm/settings/GSIM_costs.txt --gold data/local/gal/GSIM/lb005_047_gold.txt --input data/local/gal/GSIM/lb005_047_label.txt --eval data/local/gal/GSIM/lb005_047_eval.txt > data/local/gal/GSIM/lb005_047_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/GSIM_categories.txt --cost galm/settings/GSIM_costs.txt --gold data/local/gal/GSIM/lb005_048_gold.txt --input data/local/gal/GSIM/lb005_048_label.txt --eval data/local/gal/GSIM/lb005_048_eval.txt > data/local/gal/GSIM/lb005_048_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/GSIM_categories.txt --cost galm/settings/GSIM_costs.txt --gold data/local/gal/GSIM/lb005_049_gold.txt --input data/local/gal/GSIM/lb005_049_label.txt --eval data/local/gal/GSIM/lb005_049_eval.txt > data/local/gal/GSIM/lb005_049_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/GDIF_categories.txt --cost galm/settings/GDIF_costs.txt --gold data/local/gal/GDIF/lb005_000_gold.txt --input data/local/gal/GDIF/lb005_000_label.txt --eval data/local/gal/GDIF/lb005_000_eval.txt > data/local/gal/GDIF/lb005_000_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/GDIF_categories.txt --cost galm/settings/GDIF_costs.txt --gold data/local/gal/GDIF/lb005_001_gold.txt --input data/local/gal/GDIF/lb005_001_label.txt --eval data/local/gal/GDIF/lb005_001_eval.txt > data/local/gal/GDIF/lb005_001_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/GDIF_categories.txt --cost galm/settings/GDIF_costs.txt --gold data/local/gal/GDIF/lb005_002_gold.txt --input data/local/gal/GDIF/lb005_002_label.txt --eval data/local/gal/GDIF/lb005_002_eval.txt > data/local/gal/GDIF/lb005_002_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/GDIF_categories.txt --cost galm/settings/GDIF_costs.txt --gold data/local/gal/GDIF/lb005_003_gold.txt --input data/local/gal/GDIF/lb005_003_label.txt --eval data/local/gal/GDIF/lb005_003_eval.txt > data/local/gal/GDIF/lb005_003_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/GDIF_categories.txt --cost galm/settings/GDIF_costs.txt --gold data/local/gal/GDIF/lb005_004_gold.txt --input data/local/gal/GDIF/lb005_004_label.txt --eval data/local/gal/GDIF/lb005_004_eval.txt > data/local/gal/GDIF/lb005_004_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/GDIF_categories.txt --cost galm/settings/GDIF_costs.txt --gold data/local/gal/GDIF/lb005_005_gold.txt --input data/local/gal/GDIF/lb005_005_label.txt --eval data/local/gal/GDIF/lb005_005_eval.txt > data/local/gal/GDIF/lb005_005_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/GDIF_categories.txt --cost galm/settings/GDIF_costs.txt --gold data/local/gal/GDIF/lb005_006_gold.txt --input data/local/gal/GDIF/lb005_006_label.txt --eval data/local/gal/GDIF/lb005_006_eval.txt > data/local/gal/GDIF/lb005_006_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/GDIF_categories.txt --cost galm/settings/GDIF_costs.txt --gold data/local/gal/GDIF/lb005_007_gold.txt --input data/local/gal/GDIF/lb005_007_label.txt --eval data/local/gal/GDIF/lb005_007_eval.txt > data/local/gal/GDIF/lb005_007_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/GDIF_categories.txt --cost galm/settings/GDIF_costs.txt --gold data/local/gal/GDIF/lb005_008_gold.txt --input data/local/gal/GDIF/lb005_008_label.txt --eval data/local/gal/GDIF/lb005_008_eval.txt > data/local/gal/GDIF/lb005_008_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/GDIF_categories.txt --cost galm/settings/GDIF_costs.txt --gold data/local/gal/GDIF/lb005_009_gold.txt --input data/local/gal/GDIF/lb005_009_label.txt --eval data/local/gal/GDIF/lb005_009_eval.txt > data/local/gal/GDIF/lb005_009_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/GDIF_categories.txt --cost galm/settings/GDIF_costs.txt --gold data/local/gal/GDIF/lb005_010_gold.txt --input data/local/gal/GDIF/lb005_010_label.txt --eval data/local/gal/GDIF/lb005_010_eval.txt > data/local/gal/GDIF/lb005_010_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/GDIF_categories.txt --cost galm/settings/GDIF_costs.txt --gold data/local/gal/GDIF/lb005_011_gold.txt --input data/local/gal/GDIF/lb005_011_label.txt --eval data/local/gal/GDIF/lb005_011_eval.txt > data/local/gal/GDIF/lb005_011_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/GDIF_categories.txt --cost galm/settings/GDIF_costs.txt --gold data/local/gal/GDIF/lb005_012_gold.txt --input data/local/gal/GDIF/lb005_012_label.txt --eval data/local/gal/GDIF/lb005_012_eval.txt > data/local/gal/GDIF/lb005_012_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/GDIF_categories.txt --cost galm/settings/GDIF_costs.txt --gold data/local/gal/GDIF/lb005_013_gold.txt --input data/local/gal/GDIF/lb005_013_label.txt --eval data/local/gal/GDIF/lb005_013_eval.txt > data/local/gal/GDIF/lb005_013_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/GDIF_categories.txt --cost galm/settings/GDIF_costs.txt --gold data/local/gal/GDIF/lb005_014_gold.txt --input data/local/gal/GDIF/lb005_014_label.txt --eval data/local/gal/GDIF/lb005_014_eval.txt > data/local/gal/GDIF/lb005_014_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/GDIF_categories.txt --cost galm/settings/GDIF_costs.txt --gold data/local/gal/GDIF/lb005_015_gold.txt --input data/local/gal/GDIF/lb005_015_label.txt --eval data/local/gal/GDIF/lb005_015_eval.txt > data/local/gal/GDIF/lb005_015_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/GDIF_categories.txt --cost galm/settings/GDIF_costs.txt --gold data/local/gal/GDIF/lb005_016_gold.txt --input data/local/gal/GDIF/lb005_016_label.txt --eval data/local/gal/GDIF/lb005_016_eval.txt > data/local/gal/GDIF/lb005_016_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/GDIF_categories.txt --cost galm/settings/GDIF_costs.txt --gold data/local/gal/GDIF/lb005_017_gold.txt --input data/local/gal/GDIF/lb005_017_label.txt --eval data/local/gal/GDIF/lb005_017_eval.txt > data/local/gal/GDIF/lb005_017_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/GDIF_categories.txt --cost galm/settings/GDIF_costs.txt --gold data/local/gal/GDIF/lb005_018_gold.txt --input data/local/gal/GDIF/lb005_018_label.txt --eval data/local/gal/GDIF/lb005_018_eval.txt > data/local/gal/GDIF/lb005_018_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/GDIF_categories.txt --cost galm/settings/GDIF_costs.txt --gold data/local/gal/GDIF/lb005_019_gold.txt --input data/local/gal/GDIF/lb005_019_label.txt --eval data/local/gal/GDIF/lb005_019_eval.txt > data/local/gal/GDIF/lb005_019_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/GDIF_categories.txt --cost galm/settings/GDIF_costs.txt --gold data/local/gal/GDIF/lb005_020_gold.txt --input data/local/gal/GDIF/lb005_020_label.txt --eval data/local/gal/GDIF/lb005_020_eval.txt > data/local/gal/GDIF/lb005_020_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/GDIF_categories.txt --cost galm/settings/GDIF_costs.txt --gold data/local/gal/GDIF/lb005_021_gold.txt --input data/local/gal/GDIF/lb005_021_label.txt --eval data/local/gal/GDIF/lb005_021_eval.txt > data/local/gal/GDIF/lb005_021_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/GDIF_categories.txt --cost galm/settings/GDIF_costs.txt --gold data/local/gal/GDIF/lb005_022_gold.txt --input data/local/gal/GDIF/lb005_022_label.txt --eval data/local/gal/GDIF/lb005_022_eval.txt > data/local/gal/GDIF/lb005_022_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/GDIF_categories.txt --cost galm/settings/GDIF_costs.txt --gold data/local/gal/GDIF/lb005_023_gold.txt --input data/local/gal/GDIF/lb005_023_label.txt --eval data/local/gal/GDIF/lb005_023_eval.txt > data/local/gal/GDIF/lb005_023_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/GDIF_categories.txt --cost galm/settings/GDIF_costs.txt --gold data/local/gal/GDIF/lb005_024_gold.txt --input data/local/gal/GDIF/lb005_024_label.txt --eval data/local/gal/GDIF/lb005_024_eval.txt > data/local/gal/GDIF/lb005_024_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/GDIF_categories.txt --cost galm/settings/GDIF_costs.txt --gold data/local/gal/GDIF/lb005_025_gold.txt --input data/local/gal/GDIF/lb005_025_label.txt --eval data/local/gal/GDIF/lb005_025_eval.txt > data/local/gal/GDIF/lb005_025_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/GDIF_categories.txt --cost galm/settings/GDIF_costs.txt --gold data/local/gal/GDIF/lb005_026_gold.txt --input data/local/gal/GDIF/lb005_026_label.txt --eval data/local/gal/GDIF/lb005_026_eval.txt > data/local/gal/GDIF/lb005_026_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/GDIF_categories.txt --cost galm/settings/GDIF_costs.txt --gold data/local/gal/GDIF/lb005_027_gold.txt --input data/local/gal/GDIF/lb005_027_label.txt --eval data/local/gal/GDIF/lb005_027_eval.txt > data/local/gal/GDIF/lb005_027_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/GDIF_categories.txt --cost galm/settings/GDIF_costs.txt --gold data/local/gal/GDIF/lb005_028_gold.txt --input data/local/gal/GDIF/lb005_028_label.txt --eval data/local/gal/GDIF/lb005_028_eval.txt > data/local/gal/GDIF/lb005_028_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/GDIF_categories.txt --cost galm/settings/GDIF_costs.txt --gold data/local/gal/GDIF/lb005_029_gold.txt --input data/local/gal/GDIF/lb005_029_label.txt --eval data/local/gal/GDIF/lb005_029_eval.txt > data/local/gal/GDIF/lb005_029_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/GDIF_categories.txt --cost galm/settings/GDIF_costs.txt --gold data/local/gal/GDIF/lb005_030_gold.txt --input data/local/gal/GDIF/lb005_030_label.txt --eval data/local/gal/GDIF/lb005_030_eval.txt > data/local/gal/GDIF/lb005_030_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/GDIF_categories.txt --cost galm/settings/GDIF_costs.txt --gold data/local/gal/GDIF/lb005_031_gold.txt --input data/local/gal/GDIF/lb005_031_label.txt --eval data/local/gal/GDIF/lb005_031_eval.txt > data/local/gal/GDIF/lb005_031_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/GDIF_categories.txt --cost galm/settings/GDIF_costs.txt --gold data/local/gal/GDIF/lb005_032_gold.txt --input data/local/gal/GDIF/lb005_032_label.txt --eval data/local/gal/GDIF/lb005_032_eval.txt > data/local/gal/GDIF/lb005_032_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/GDIF_categories.txt --cost galm/settings/GDIF_costs.txt --gold data/local/gal/GDIF/lb005_033_gold.txt --input data/local/gal/GDIF/lb005_033_label.txt --eval data/local/gal/GDIF/lb005_033_eval.txt > data/local/gal/GDIF/lb005_033_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/GDIF_categories.txt --cost galm/settings/GDIF_costs.txt --gold data/local/gal/GDIF/lb005_034_gold.txt --input data/local/gal/GDIF/lb005_034_label.txt --eval data/local/gal/GDIF/lb005_034_eval.txt > data/local/gal/GDIF/lb005_034_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/GDIF_categories.txt --cost galm/settings/GDIF_costs.txt --gold data/local/gal/GDIF/lb005_035_gold.txt --input data/local/gal/GDIF/lb005_035_label.txt --eval data/local/gal/GDIF/lb005_035_eval.txt > data/local/gal/GDIF/lb005_035_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/GDIF_categories.txt --cost galm/settings/GDIF_costs.txt --gold data/local/gal/GDIF/lb005_036_gold.txt --input data/local/gal/GDIF/lb005_036_label.txt --eval data/local/gal/GDIF/lb005_036_eval.txt > data/local/gal/GDIF/lb005_036_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/GDIF_categories.txt --cost galm/settings/GDIF_costs.txt --gold data/local/gal/GDIF/lb005_037_gold.txt --input data/local/gal/GDIF/lb005_037_label.txt --eval data/local/gal/GDIF/lb005_037_eval.txt > data/local/gal/GDIF/lb005_037_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/GDIF_categories.txt --cost galm/settings/GDIF_costs.txt --gold data/local/gal/GDIF/lb005_038_gold.txt --input data/local/gal/GDIF/lb005_038_label.txt --eval data/local/gal/GDIF/lb005_038_eval.txt > data/local/gal/GDIF/lb005_038_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/GDIF_categories.txt --cost galm/settings/GDIF_costs.txt --gold data/local/gal/GDIF/lb005_039_gold.txt --input data/local/gal/GDIF/lb005_039_label.txt --eval data/local/gal/GDIF/lb005_039_eval.txt > data/local/gal/GDIF/lb005_039_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/GDIF_categories.txt --cost galm/settings/GDIF_costs.txt --gold data/local/gal/GDIF/lb005_040_gold.txt --input data/local/gal/GDIF/lb005_040_label.txt --eval data/local/gal/GDIF/lb005_040_eval.txt > data/local/gal/GDIF/lb005_040_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/GDIF_categories.txt --cost galm/settings/GDIF_costs.txt --gold data/local/gal/GDIF/lb005_041_gold.txt --input data/local/gal/GDIF/lb005_041_label.txt --eval data/local/gal/GDIF/lb005_041_eval.txt > data/local/gal/GDIF/lb005_041_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/GDIF_categories.txt --cost galm/settings/GDIF_costs.txt --gold data/local/gal/GDIF/lb005_042_gold.txt --input data/local/gal/GDIF/lb005_042_label.txt --eval data/local/gal/GDIF/lb005_042_eval.txt > data/local/gal/GDIF/lb005_042_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/GDIF_categories.txt --cost galm/settings/GDIF_costs.txt --gold data/local/gal/GDIF/lb005_043_gold.txt --input data/local/gal/GDIF/lb005_043_label.txt --eval data/local/gal/GDIF/lb005_043_eval.txt > data/local/gal/GDIF/lb005_043_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/GDIF_categories.txt --cost galm/settings/GDIF_costs.txt --gold data/local/gal/GDIF/lb005_044_gold.txt --input data/local/gal/GDIF/lb005_044_label.txt --eval data/local/gal/GDIF/lb005_044_eval.txt > data/local/gal/GDIF/lb005_044_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/GDIF_categories.txt --cost galm/settings/GDIF_costs.txt --gold data/local/gal/GDIF/lb005_045_gold.txt --input data/local/gal/GDIF/lb005_045_label.txt --eval data/local/gal/GDIF/lb005_045_eval.txt > data/local/gal/GDIF/lb005_045_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/GDIF_categories.txt --cost galm/settings/GDIF_costs.txt --gold data/local/gal/GDIF/lb005_046_gold.txt --input data/local/gal/GDIF/lb005_046_label.txt --eval data/local/gal/GDIF/lb005_046_eval.txt > data/local/gal/GDIF/lb005_046_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/GDIF_categories.txt --cost galm/settings/GDIF_costs.txt --gold data/local/gal/GDIF/lb005_047_gold.txt --input data/local/gal/GDIF/lb005_047_label.txt --eval data/local/gal/GDIF/lb005_047_eval.txt > data/local/gal/GDIF/lb005_047_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/GDIF_categories.txt --cost galm/settings/GDIF_costs.txt --gold data/local/gal/GDIF/lb005_048_gold.txt --input data/local/gal/GDIF/lb005_048_label.txt --eval data/local/gal/GDIF/lb005_048_eval.txt > data/local/gal/GDIF/lb005_048_result.txt
call galm/bin/get-another-label.bat --categories galm/settings/GDIF_categories.txt --cost galm/settings/GDIF_costs.txt --gold data/local/gal/GDIF/lb005_049_gold.txt --input data/local/gal/GDIF/lb005_049_label.txt --eval data/local/gal/GDIF/lb005_049_eval.txt > data/local/gal/GDIF/lb005_049_result.txt
